OneSignal/cli

lib/osproject_ios.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/8)

Document next steps for user

---

lib/osproject_android.rb

* Change from Regexp to String
* Add regaex matching with ""
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/9)

Fix build.gradle matching/replace

---

lib/osproject_android.rb

* Add class and onCreate matching
* Add OneSignal init lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/10)

Add Application matching

---

lib/oscli.rb
lib/osproject_android.rb

* Fix lang comparison, convert lang to string, and compare to string
* Add entrypoint to GoogleAndroid method call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/11)

Fix missing param and String comparison

---

lib/osproject_android.rb

* Some apps might have changed the app directory name, get the directory from the Application class directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/12)

Add app directory parsing

---

lib/osproject_android.rb

* The project might have not configured a custom application class, create it for the user
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/13)

Add Application class creation

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/14)

Add Android README information

---

README.md

Add platform's example
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/15)

Add Example by type

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/16)

Add instructions for Application creation

---

lib/osproject_android.rb

* If line was already added avoid adding again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/17)

Add duplicate check

---

lib/osproject_android.rb

* Add logs for failing steps
* Add successful message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/19)

Add File not found error handling logging

---

README.md
lib/oscli.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/20)

Add Readme documentation and help documentation command

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/21)

[Documentation] Add backticks to some commands

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/22)

[Documentation] Specify limitations of the CLI

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/23)

[Documentation] fix README s/platform/os/

---

lib/osproject_android.rb
lib/osproject_helpers.rb

* Only include changes made to success message
* Fix generated code indentation
* Fix typo Directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/24)

Improve printed success message

---

lib/oscli.rb
lib/osproject_android.rb

* Make took parameters easier for calling
* Get android directory from the calling path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/27)

Change parameters to options

---

lib/oscli.rb

Track install-sdk validations error tracking
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/31)

Add install-sdk command error tracking

---

lib/oscli.rb
lib/osproject_ios.rb

* Send CLI version, OS, platform, language, application Id, actions taken by the CLI and error logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/30)

Add iOS user steps tracking

---

lib/oscli.rb
lib/osnetwork.rb
lib/osproject.rb
lib/osproject_android.rb
lib/osproject_ios.rb

Add Android tracking 
* Add tracking API request
* Send CLI version, OS, platform, language, application Id, actions taken by the CLI, and error logging
Abstract API request to the new class 
* Create Singleton NetworkHandler class
* Make NetworkHandler responsible for tracking request
Add generic commands tracking 
* Track version, help, and available-commands commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/cli/29)

Add tracking logic
